### ISSUE TITLE
ImportError: No module named 'cymetric.cyclus'

### ISSUE THREAD

**Issue by bam241** [cyclus/cyclus.github.com#228]
there is no cyclus module in symmetric anymore this lead to an error when trying to update the website:
```
/Users/mouginot/work/website/cyclus.github.com/source/user/cymetric/api/cyclus.rst:7: WARNING: autodoc: failed to import module 'cymetric.cyclus'; the following exception was raised:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
    __import__(self.modname)
ImportError: No module named 'cymetric.cyclus'


/Users/mouginot/work/website/cyclus.github.com/source/user/cymetric/api/typesystem.rst:7: WARNING: autodoc: failed to import module 'cymetric.typesystem'; the followi


ng exception was raised:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
    __import__(self.modname)
ImportError: No module named 'cymetric.typesystem'
```

**Comment by scopatz** [comment]
Right, you need to update to cymetric v1.5

**Comment by Baaaaam** [comment]
@scopatz I don't understand, my local `cymetric` is uptodate...
And I also update the docker container.

is it not because Cymetric is a full Python lib (and some of the "stuff" that use to be in Cymetric are now in the cyclus Python lib ?)

**Comment by scopatz** [comment]
Oh! It is probably because the autodoc hooks here were not updated. See https://github.com/cyclus/cyclus.github.com/tree/source/source/user/cymetric/api

**Comment by bam241** [comment]
@scopatz this is is fixed right ?!

**Comment by scopatz** [comment]
Yes, I think so.
